// src/utils/aadhaarScenarios.js

export const UPDATE_SCENARIOS = [
  { category: "Minor Name Change", code: "(a)", description: "Expanding the abbreviation or abbreviating the name to initials", target: "All residents / Minors (<18 yrs for HoF)", illustrations: "T R D Prasad to Tadi Rama Durga Prasad; Ram Mohan Naidu to RM Naidu or Naidu RM or R M Naidu", docs: "PoI / Applicable PoR in cases of HoF-based name update of children (less than 18 years)", exceptions: "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document." },
  { category: "Minor Name Change", code: "(b)", description: "Addition or deletion of middle name(s) or last name", target: "All residents / Minors (<18 yrs for HoF)", illustrations: "Addition: Himanshu Gupta to Himanshu Chandra Gupta; Deletion: Himanshu Chandra Gupta to Himanshu Gupta", docs: "PoI / Applicable PoR in cases of HoF-based name update of children", exceptions: "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document." },
  { category: "Minor Name Change", code: "(c)", description: "Change in sequential order", target: "All residents / Minors (<18 yrs for HoF)", illustrations: "Divakar Anand to Anand Divakar; Ravi Kishan to Kishan Ravi", docs: "PoI / Applicable PoR in cases of HoF-based name update of children", exceptions: "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document." },
  { category: "Minor Name Change", code: "(d)", description: "There is a minor correction in English spelling, however names are phonetically similar", target: "All residents / Minors (<18 yrs for HoF)", illustrations: "Ram to Rama; Sitaram to Sita Ram; Somya to Saumya; Pooja Singh to Puja Singh", docs: "PoI / Applicable PoR in cases of HoF-based name update of children", exceptions: "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document." },
  { category: "Minor Name Change", code: "(e)", description: "Any combination of (a), (b), (c) and (d)", target: "All residents / Minors (<18 yrs for HoF)", illustrations: "Not in source", docs: "PoI / Applicable PoR in cases of HoF-based name update of children", exceptions: "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document." },
  { category: "Major Name Change", code: "(o)", description: "Complete change of name / change of identity", target: "Not in source", illustrations: "Ram Gupta to Shyam Gupta; Amisha Patel to Ameesha Kumar Singh", docs: "PoI (only Gazette Notification for name change)", exceptions: "Complete change in name / change of identity is liable to be rejected if not accompanied by a Gazette Notification." },
  { category: "Special Cases", code: "(h)", description: "Change of surname of women, post marriage or divorce", target: "Women", illustrations: "Gita Rai to Gita Siddharth Rai; Reeta Rai to Reeta Krishna Mohan", docs: "Affidavit (Annexure D) & PoI", exceptions: "Affidavit on Non-Judicial Stamp Paper of minimum value of ₹10 signed and attested in presence of Judicial Magistrate or Executive Magistrate/Notary Public." },
  { category: "Special Cases", code: "(i)", description: "Change of name due to change of gender", target: "Not in source", illustrations: "Sarita Kumari to Santosh Kumar", docs: "Applicable PoI", exceptions: "Not in source" },
  { category: "Special Cases", code: "(j)", description: "HoF-based name update of child (less than 18 years of age) from 'Baby of _' to any name", target: "Minors (less than 18 years of age)", illustrations: "Baby of Sudha to Ritu Kumar; Baby to Rahul Singh", docs: "Applicable PoR", exceptions: "Not in source" },
  { category: "Special Cases", code: "(k)", description: "Dropping of ranks, designations, and other such prefixes", target: "Not in source", illustrations: "Military ranks such as Lt Gen, Maj Gen, Brig, Col... Justice, Prof, Retd, Dr, Learned, Shri, Smt, Ms, Mr etc.", docs: "PoI", exceptions: "Not in source" },
  { category: "Special Cases", code: "(l)", description: "Correction of randomly occurring capital letters recorded in name", target: "Not in source", illustrations: "RaMesh to Ramesh; ViVEK to Vivek", docs: "No document required", exceptions: "Not in source" },
  { category: "Special Cases", code: "(m)", description: "Removal of dots from name", target: "Not in source", illustrations: "R.V.N Srinivas to RVN Srinivas; R.P. Singh to R P Singh", docs: "No document required", exceptions: "Not in source" },
  { category: "Special Cases", code: "(n)", description: "Name recorded in Aadhaar with an 'urf' or 'alias'. Necessitates removal of 'urf' or 'alias' from name", target: "Adults / Minors", illustrations: "Jagdish Singh urf Jagga to either Jagdish Singh or Jagga", docs: "For adults: Affidavit (Annexure E) & PoI. For minors: Affidavit (Annexure F) & PoI / PoR.", exceptions: "Affidavit on Non-Judicial Stamp Paper of minimum value of ₹10 signed and attested in presence of Judicial Magistrate or Executive Magistrate/Notary Public." },
  { category: "Data Entry Error", code: "(f)", description: "Name was incorrectly recorded in Aadhaar; however, the previously submitted document carried the correct name.", target: "Adults / Minors", illustrations: "If the name in the instant update request matches the name in previously submitted PoI/PoR document available with UIDAI, then the instant update request shall be accepted.", docs: "For adults: Affidavit (Annexure B) & PoI / PoR. For minors: Affidavit (Annexure C) & PoI / PoR.", exceptions: "If the name in the instant update request does not match the name in previously submitted PoI/PoR document available with UIDAI, then the instant update request shall be rejected." },
  { category: "Error in Regional Language", code: "(g)", description: "Name in English was correctly recorded in Aadhaar, however the name in regional language is incorrect.", target: "Not in source", illustrations: "Nirmal Sinha (निर्मला सिन्हा) to Nirmal Sinha (निर्मल सिन्हा)", docs: "PoI", exceptions: "Not in source" },
  { category: "Date of Birth Update First Time", code: "Case 1 a)", description: "Existing DoB in Aadhaar is 'declared' or 'approximate'", target: "Indian Residents (0-5 years, 5-18 years, 18 years and above)", illustrations: "Not in source", docs: "Permitted PDB document as mentioned in List-IV; Birth Certificate is mandatory for age groups 0-5 years and 5-18 years", exceptions: "If ANH submitted Birth Certificate during enrolment or update as supporting document, it shall be handled as 'verified' based on birth certificate under Case 1 b) i)" },
  { category: "Date of Birth Update First Time", code: "Case 1 b) i)", description: "DoB was recorded as 'verified' in Aadhaar database based on Birth Certificate", target: "All Indian residents", illustrations: "Not in source", docs: "Corrected Birth Certificate with the same BRN and issued by the same registrar as earlier, along with an affidavit (Annex-I for adults or Annex-IA for children)", exceptions: "No need for DoB update under normal circumstances. If a document other than Birth Certificate, or a Birth Certificate with a different BRN or from a different registrar is submitted, the update request shall be rejected." },
  { category: "Date of Birth Update First Time", code: "Case 1 b) ii)", description: "DoB was recorded as 'verified' in Aadhaar database based on PDB document other than Birth Certificate", target: "Indian residents 18 years of age or above (does NOT apply to children below 18 years)", illustrations: "Not in source", docs: "Corrected version of the same document (from the existing list of valid PDB documents) or a Birth Certificate along with an affidavit (Annex-I)", exceptions: "If the document submitted earlier is not a part of the current list of valid PDB documents, then the only document admissible would be a Birth Certificate." },
  { category: "Subsequent DoB Update", code: "Case 2 a)", description: "Subsequent DoB updates after the first update done since enrolment", target: "All Indian residents / NRIs", illustrations: "Not in source", docs: "Birth Certificate (if earlier PDB was not BC) or corrected Birth Certificate with same BRN and registrar (if earlier was BC), along with an affidavit", exceptions: "Processed only on submission of Birth Certificate/corrected Birth Certificate along with affidavit." },
  { category: "Subsequent DoB Update", code: "Case 3 a)", description: "Enrolment in 0-5 years of age and subsequent DoB update requested age is more than 5 and less than 18 years", target: "Minors (requested age > 5 and < 18 years)", illustrations: "Not in source", docs: "Not in source", exceptions: "Legal action may be initiated against HoF and Aadhaar centre operator. Aadhaar omitted/deactivated." },
  { category: "Subsequent DoB Update", code: "Case 3 b)", description: "Enrolment in 0-5 years of age and subsequent DoB update requested age is 18 years or above", target: "18 years or above", illustrations: "Not in source", docs: "Not in source", exceptions: "Legal action must be initiated against ANH, HoF, and operator. Aadhaar omitted/deactivated." },
  { category: "Subsequent DoB Update", code: "Case 4 a)", description: "Enrolment in 5-18 years of age and trying to update age to more than 18 years on the date of enrolment", target: "5-18 years age group at enrolment", illustrations: "Not in source", docs: "Not in source", exceptions: "Clearly a case of fraud. Legal action may be initiated against ANH, HoF, and operator. Aadhaar deactivated." },
  { category: "Operator Error", code: "Case 1 c)", description: "Cases where operator error is alleged during first-time DoB update", target: "Indian Residents and NRIs", illustrations: "Not in source", docs: "Same document as earlier submitted (if still valid PDB document), or Self-declaration (Annex-II for adults or Annex-IIA for children)", exceptions: "DoB update count shall not be increased for such cases. Applicable to NRIs except NRIs below 18 years may submit Birth Certificate or Indian Passport." },
  { category: "Operator Error", code: "Case 2 b)", description: "Cases where operator error is alleged during subsequent DoB update", target: "Indian Residents / NRIs", illustrations: "Not in source", docs: "Same document as earlier submitted (if still valid PDB document), or Self-declaration (Annex-II for adults or Annex-IIA for children)", exceptions: "The DoB update count shall not be increased for such cases." },
  { category: "Operator Error", code: "Case 5 a)", description: "Resident Foreigners DoB updates (DoB in Aadhaar differs from Pol cum PDB document due to operator error)", target: "Resident Foreigners", illustrations: "Not in source", docs: "PoI cum PDB document and Self-declaration (Annex-II)", exceptions: "DoB update count shall not be increased. Packet moves through normal QC flow and visible on QC portal." }
];