// src/utils/aadhaarDocuments.js

export const AADHAAR_DOCUMENTS = [
  { id: "1", name: "Valid Indian Passport", poi: true, poa: true, por: true, pdb: true, notes: "Valid Indian passport. DOB conditions (#) apply." },
  { id: "2", name: "Ration / PDS Photograph Card / e-Ration Card", poi: true, poa: true, por: true, pdb: false, notes: "" },
  { id: "3", name: "Voter Identity Card / e-Voter Identity Card", poi: true, poa: true, por: false, pdb: false, notes: "Details must be displayed online on the website of the Election Commission of India or the Chief Electoral Officer concerned." },
  { id: "4", name: "Driving licence", poi: true, poa: false, por: false, pdb: false, notes: "" },
  { id: "5", name: "Service Photo Identity Card issued by Central / State Government / PSU / regulatory body", poi: true, poa: true, por: false, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "6", name: "Pensioner Photo Identity Card / Freedom Fighter Photo Identity Card / Pension Payment Order", poi: true, poa: true, por: true, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "7", name: "Kisan Photo Passbook", poi: true, poa: true, por: false, pdb: false, notes: "" },
  { id: "8", name: "CGHS / ECHS / ESIC / Medi-Claim Card issued by Central / State Government / PSU", poi: true, poa: false, por: false, pdb: false, notes: "" },
  { id: "9", name: "Certificate in UIDAI prescribed format, jointly signed and stamped by Head of Shelter Home and District Social Welfare Officer", poi: true, poa: true, por: false, pdb: false, notes: "For destitute persons with disability only." },
  { id: "10", name: "MGNREGA / NREGS Job Card and Domicile Certificate issued by State Government", poi: true, poa: true, por: true, pdb: false, notes: "Job Card together with the Domicile Certificate." },
  { id: "11", name: "Marriage Certificate with or without photograph", poi: true, poa: true, por: true, pdb: false, notes: "If no photograph, a PoI document bearing old name with photograph is also required." },
  { id: "12", name: "Divorce Decree issued by family court", poi: true, poa: false, por: false, pdb: false, notes: "If no photograph, a PoI document bearing old name with photograph is also required." },
  { id: "13", name: "ST / SC / OBC Certificate issued by Central / State Government", poi: true, poa: true, por: true, pdb: false, notes: "" },
  { id: "14", name: "Marksheet / Certificate issued by a recognised Board of Education or University", poi: true, poa: false, por: true, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "15", name: "Passbook issued by a scheduled commercial bank, State cooperative bank, or Post Office", poi: false, poa: true, por: false, pdb: false, notes: "Must be cross-stamped with bank seal and signed by an official." },
  { id: "16", name: "Bank / Credit Card / Post Office Savings Account Statement", poi: false, poa: true, por: false, pdb: false, notes: "Must carry stamp and signature of the issuing official. Not older than 3 months." },
  { id: "17", name: "Third gender / Transgender Identity Card or Certificate", poi: true, poa: true, por: true, pdb: true, notes: "Also acceptable for gender and full-name change. DOB conditions (#) apply." },
  { id: "18", name: "Gazette notification", poi: true, poa: false, por: false, pdb: false, notes: "Accepted for a change in first name or in full name." },
  { id: "19 i", name: "UIDAI Standard Format: MP / MLA / MLC / Municipal Councillor", poi: false, poa: true, por: false, pdb: false, notes: "Valid 3 months from date of issue." },
  { id: "19 ii", name: "UIDAI Standard Format: Gazetted Officer Group 'A' / EPFO Officer", poi: false, poa: true, por: false, pdb: false, notes: "Valid 3 months from date of issue." },
  { id: "19 iii", name: "UIDAI Standard Format: Tehsildar / Gazetted Officer Group 'B'", poi: false, poa: true, por: false, pdb: false, notes: "Valid 3 months from date of issue." },
  { id: "19 iv", name: "UIDAI Standard Format: Gazetted Officer at NACO / State Health Dept", poi: true, poa: true, por: false, pdb: false, notes: "Valid 3 months from date of issue. Also counts as PoI." },
  { id: "19 v", name: "UIDAI Standard Format: District Child Protection Officer (DCPO) + placement order", poi: true, poa: true, por: false, pdb: false, notes: "For children in Child Care Institutions only. Also counts as PoI." },
  { id: "19 vi", name: "UIDAI Standard Format: Recognised educational institution (signed by Head of Institute)", poi: false, poa: true, por: false, pdb: false, notes: "Only for the institute's own students. Valid 3 months from date of issue." },
  { id: "19 vii", name: "UIDAI Standard Format: Village Panchayat Head / Mukhiya / Village Revenue Officer", poi: false, poa: true, por: false, pdb: false, notes: "For rural areas only. Valid 3 months from date of issue." },
  { id: "20", name: "Electricity bill (pre-paid / post-paid)", poi: false, poa: true, por: false, pdb: false, notes: "Not older than 3 months." },
  { id: "21", name: "Water bill", poi: false, poa: true, por: false, pdb: false, notes: "Not older than 3 months." },
  { id: "22", name: "Telephone landline bill / post-paid mobile bill / broadband bill", poi: false, poa: true, por: false, pdb: false, notes: "Not older than 3 months." },
  { id: "23", name: "Property Tax Receipt", poi: false, poa: true, por: false, pdb: false, notes: "Not older than 1 year." },
  { id: "24", name: "Valid sale agreement / gift deed / registered or unregistered rent agreement", poi: false, poa: true, por: false, pdb: false, notes: "" },
  { id: "25", name: "Gas bill", poi: false, poa: true, por: false, pdb: false, notes: "Not older than 3 months." },
  { id: "26", name: "Allotment letter of accommodation issued by Central / State Government / PSU", poi: false, poa: true, por: false, pdb: false, notes: "Not older than 1 year." },
  { id: "27", name: "Life or medical insurance policy", poi: false, poa: true, por: false, pdb: false, notes: "Valid up to 1 year from the date of issue." },
  { id: "28", name: "Birth certificate issued under the Registration of Births and Deaths Act, 1969", poi: false, poa: false, por: true, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "29", name: "Prisoner Induction Document (PID) issued by Prison Officer", poi: true, poa: true, por: false, pdb: false, notes: "For prisoners only." },
  { id: "30", name: "Self-declaration from an immediate family member certifying relationship", poi: false, poa: false, por: true, pdb: false, notes: "Valid only for borrowing address. HoF form is valid 3 months." },
  { id: "31", name: "Document proving legal guardianship issued by Central / State Govt or court of law", poi: false, poa: false, por: true, pdb: false, notes: "Counts as Proof of Relationship (PoR) only." },
  { id: "32", name: "OCI cardholders - valid foreign passport (along with OCI card)", poi: true, poa: false, por: false, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "33 a", name: "Nepal / Bhutan nationals - Passport of Nepal / Bhutan", poi: true, poa: false, por: false, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "33 b", name: "Nepal / Bhutan nationals - Citizenship Certificate / Voter ID / Identity Certificate", poi: true, poa: false, por: false, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "34", name: "Long Term Visa (LTV) holders - valid LTV", poi: true, poa: true, por: false, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "35", name: "Other foreign nationals - valid foreign passport (along with valid visa)", poi: true, poa: false, por: false, pdb: true, notes: "DOB conditions (#) apply." },
  { id: "36", name: "Valid Registration Certificate or Residential permit issued by FRRO / FRO", poi: true, poa: true, por: false, pdb: true, notes: "DOB conditions (#) apply." },
];