// Generated from Aadhaar_Update_Procedure_Finder.xlsx (Data, Rules and Source References tabs).
// Edit here when UIDAI changes a scenario. 'code' must stay unique.
export const SCENARIOS = [
  {
    "code": "(a)",
    "category": "Minor Name Change",
    "description": "Expanding the abbreviation or abbreviating the name to initials",
    "appliesTo": "All residents / Minors (<18 yrs for HoF)",
    "examples": "T R D Prasad to Tadi Rama Durga Prasad; Ram Mohan Naidu to RM Naidu or Naidu RM or R M Naidu; V V R S Shastri to Varanasi Venkata Ramanuja Shiva Shastri, Varanasi Venkata Ramanuja Shiva Shastri to VVRS Shastri; Mohd to Md or Mohammad or Muhammad; CA Tirkey to Cornelius Ajas Tirkey",
    "documents": "PoI / Applicable PoR in cases of HoF-based name update of children (less than 18 years)",
    "exceptions": "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(b)",
    "category": "Minor Name Change",
    "description": "Addition or deletion of middle name(s) or last name",
    "appliesTo": "All residents / Minors (<18 yrs for HoF)",
    "examples": "Addition: Himanshu Gupta to Himanshu Chandra Gupta or Himanshu Bhimrao Keshav Gupta, Sanapala Rao to Sanapala Bhushan Rao, Tadi Rama Prasad to Tadi Rama Shyam Prasad. Deletion: Himanshu Chandra Gupta to Himanshu Gupta, Lakshmi Jyoti Swaroopini to Jyoti Swaroopini, Vishu Kumar to Vishu.",
    "documents": "PoI / Applicable PoR in cases of HoF-based name update of children (less than 18 years)",
    "exceptions": "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(c)",
    "category": "Minor Name Change",
    "description": "Change in sequential order",
    "appliesTo": "All residents / Minors (<18 yrs for HoF)",
    "examples": "Divakar Anand to Anand Divakar; Ravi Kishan to Kishan Ravi",
    "documents": "PoI / Applicable PoR in cases of HoF-based name update of children (less than 18 years)",
    "exceptions": "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(d)",
    "category": "Minor Name Change",
    "description": "There is a minor correction in English spelling, however names are phonetically similar",
    "appliesTo": "All residents / Minors (<18 yrs for HoF)",
    "examples": "Ram to Rama; Sitaram to Sita Ram; Somya to Saumya; Pooja Singh to Puja Singh; Sanjeev Kumar to Sanjiv Kumar; Abhishek to Abhisek; Velayutham to Velayudham; Chidambaram to Sidambaram; Dhanalakshmi to Dhanalakshmi",
    "documents": "PoI / Applicable PoR in cases of HoF-based name update of children (less than 18 years)",
    "exceptions": "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(e)",
    "category": "Minor Name Change",
    "description": "Any combination of (a), (b), (c) and (d)",
    "appliesTo": "All residents / Minors (<18 yrs for HoF)",
    "examples": null,
    "documents": "PoI / Applicable PoR in cases of HoF-based name update of children (less than 18 years)",
    "exceptions": "Name shall be updated as per the spelling, sequence, abbreviation etc. mentioned in the submitted document.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(o)",
    "category": "Major Name Change",
    "description": "Complete change of name / change of identity",
    "appliesTo": null,
    "examples": "Ram Gupta to Shyam Gupta; Amisha Patel to Ameesha Kumar Singh",
    "documents": "PoI (only Gazette Notification for name change)",
    "exceptions": "Complete change in name / change of identity is liable to be rejected if not accompanied by a Gazette Notification.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(h)",
    "category": "Special Cases",
    "description": "Change of surname of women, post marriage or divorce",
    "appliesTo": "Women",
    "examples": "Gita Rai to Gita Siddharth Rai; Reeta Rai to Reeta Krishna Mohan; Amisha Patel to Amisha Singh",
    "documents": "Affidavit (Annexure D) & PoI",
    "exceptions": "Affidavit on Non-Judicial Stamp Paper of minimum value of ₹10 signed and attested in presence of Judicial Magistrate or Executive Magistrate/Notary Public.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": "Annexure D",
    "annexureMinor": "Annexure D"
  },
  {
    "code": "(i)",
    "category": "Special Cases",
    "description": "Change of name due to change of gender",
    "appliesTo": null,
    "examples": "Sarita Kumari to Santosh Kumar",
    "documents": "Applicable PoI",
    "exceptions": null,
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(j)",
    "category": "Special Cases",
    "description": "HoF-based name update of child (less than 18 years of age) from \"Baby of _\" to any name",
    "appliesTo": "Minors (less than 18 years of age)",
    "examples": "Baby of Sudha to Ritu Kumar; Baby to Rahul Singh",
    "documents": "Applicable PoR",
    "exceptions": null,
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(k)",
    "category": "Special Cases",
    "description": "Dropping of ranks, designations, and other such prefixes",
    "appliesTo": null,
    "examples": "Military ranks such as Lt Gen, Maj Gen, Brig, Col, Lt Col, Sub Maj, Sub, Nb Sub, Hav, Nk, L Nk etc. Justice, Prof, Retd, Dr, Learned, Ld etc. Shri, Smt, Ms, Mr etc.",
    "documents": "PoI",
    "exceptions": null,
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(l)",
    "category": "Special Cases",
    "description": "Correction of randomly occurring capital letters recorded in name",
    "appliesTo": null,
    "examples": "RaMesh to Ramesh; ViVEK to Vivek",
    "documents": "No document required",
    "exceptions": null,
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(m)",
    "category": "Special Cases",
    "description": "Removal of dots from name",
    "appliesTo": null,
    "examples": "R.V.N Srinivas to RVN Srinivas; R.P. Singh to R P Singh; R P Singh. to R P Singh",
    "documents": "No document required",
    "exceptions": null,
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "(n)",
    "category": "Special Cases",
    "description": "Name recorded in Aadhaar with an 'urf' or 'alias'. Necessitates removal of \"urf\" or 'alias' from name",
    "appliesTo": "Adults / Minors",
    "examples": "Jagdish Singh urf Jagga to either Jagdish Singh or Jagga; Rahul Singh urf Bittu to either Rahul Singh or Bittu",
    "documents": "For adults: Affidavit (Annexure E) & PoI. For minors: Affidavit (Annexure F) & PoI / PoR.",
    "exceptions": "Affidavit on Non-Judicial Stamp Paper of minimum value of ₹10 signed and attested in presence of Judicial Magistrate or Executive Magistrate/Notary Public.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": "Annexure E",
    "annexureMinor": "Annexure F"
  },
  {
    "code": "(f)",
    "category": "Data Entry Error",
    "description": "Name was incorrectly recorded in Aadhaar; however, the previously submitted document carried the correct name.",
    "appliesTo": "Adults / Minors",
    "examples": "If the name in the instant update request matches the name in previously submitted PoI/PoR document available with UIDAI, then the instant update request shall be accepted.",
    "documents": "For adults: Affidavit (Annexure B) & PoI / PoR. For minors: Affidavit (Annexure C) & PoI / PoR.",
    "exceptions": "If the name in the instant update request does not match the name in previously submitted PoI/PoR document available with UIDAI, then the instant update request shall be rejected. Affidavit on Non-Judicial Stamp Paper of minimum value of ₹10 signed and attested in presence of Judicial Magistrate or Executive Magistrate/Notary Public.",
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": "Annexure B",
    "annexureMinor": "Annexure C"
  },
  {
    "code": "(g)",
    "category": "Error in Regional Language",
    "description": "Name in English was correctly recorded in Aadhaar, however the name in regional language is incorrect.",
    "appliesTo": null,
    "examples": "Nirmal Sinha (निर्मला सिन्हा) to Nirmal Sinha (निर्मल सिन्हा)",
    "documents": "PoI",
    "exceptions": null,
    "source": "SoP for Name Update dt 18Sep2026.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "Case 1 a)",
    "category": "Date of Birth Update First Time",
    "description": "Existing DoB in Aadhaar is 'declared' or 'approximate'",
    "appliesTo": "Indian Residents (0-5 years, 5-18 years, 18 years and above)",
    "examples": null,
    "documents": "Permitted PDB document as mentioned in List-IV; Birth Certificate is mandatory for age groups 0-5 years and 5-18 years",
    "exceptions": "If ANH submitted Birth Certificate during enrolment or update as supporting document, it shall be handled as 'verified' based on birth certificate under Case 1 b) i)",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": false,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "Case 1 b) i)",
    "category": "Date of Birth Update First Time",
    "description": "DoB was recorded as 'verified' in Aadhaar database based on Birth Certificate",
    "appliesTo": "All Indian residents",
    "examples": null,
    "documents": "Corrected Birth Certificate with the same BRN and issued by the same registrar as earlier, along with an affidavit (Annex-I for adults or Annex-IA for children)",
    "exceptions": "No need for DoB update under normal circumstances. If a document other than Birth Certificate, or a Birth Certificate with a different BRN or from a different registrar is submitted, the update request shall be rejected.",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": false,
    "annexureAdult": "Annex-I",
    "annexureMinor": "Annex-IA"
  },
  {
    "code": "Case 1 b) ii)",
    "category": "Date of Birth Update First Time",
    "description": "DoB was recorded as 'verified' in Aadhaar database based on PDB document other than Birth Certificate",
    "appliesTo": "Indian residents 18 years of age or above (does NOT apply to children below 18 years)",
    "examples": null,
    "documents": "Corrected version of the same document (from the existing list of valid PDB documents) or a Birth Certificate along with an affidavit (Annex-I)",
    "exceptions": "If the document submitted earlier is not a part of the current list of valid PDB documents, then the only document admissible would be a Birth Certificate. Does NOT apply to children below 18 years of age.",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": false,
    "annexureAdult": "Annex-I",
    "annexureMinor": "Not applicable (adults only)"
  },
  {
    "code": "Case 2 a)",
    "category": "Subsequent DoB Update",
    "description": "Subsequent DoB updates after the first update done since enrolment",
    "appliesTo": "All Indian residents / NRIs",
    "examples": null,
    "documents": "Birth Certificate (if earlier PDB document was not a Birth Certificate) or corrected Birth Certificate with same BRN and registrar (if earlier PDB document was a Birth Certificate), along with an affidavit (Annex-I for adults or Annex-IA for children)",
    "exceptions": "Processed only on submission of Birth Certificate/corrected Birth Certificate along with affidavit.",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": false,
    "annexureAdult": "Annex-I",
    "annexureMinor": "Annex-IA"
  },
  {
    "code": "Case 3 a)",
    "category": "Subsequent DoB Update",
    "description": "Enrolment in 0-5 years of age and subsequent DoB update requested age is more than 5 and less than 18 years",
    "appliesTo": "Minors (requested age > 5 and < 18 years)",
    "examples": null,
    "documents": null,
    "exceptions": "Legal action may be initiated against HoF and Aadhaar centre operator. Aadhaar omitted/deactivated under regulation 28 (1) (ca) if biometric available, or regulation 27 (2) if biometric not available.",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": true,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "Case 3 b)",
    "category": "Subsequent DoB Update",
    "description": "Enrolment in 0-5 years of age and subsequent DoB update requested age is 18 years or above",
    "appliesTo": "18 years or above",
    "examples": null,
    "documents": null,
    "exceptions": "Legal action must be initiated against ANH, HoF, and operator. Aadhaar omitted/deactivated under regulation 28 (1) (ca) if biometric available, or regulation 27 (2) if biometric not available.",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": true,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "Case 4 a)",
    "category": "Subsequent DoB Update",
    "description": "Enrolment in 5-18 years of age and trying to update age to more than 18 years on the date of enrolment",
    "appliesTo": "5-18 years age group at enrolment",
    "examples": null,
    "documents": null,
    "exceptions": "Clearly a case of fraud. Legal action may be initiated against ANH, HoF, and operator. Aadhaar deactivated as per regulation 28 (1) (c).",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": true,
    "annexureAdult": null,
    "annexureMinor": null
  },
  {
    "code": "Case 1 c)",
    "category": "Operator Error",
    "description": "Cases where operator error is alleged during first-time DoB update",
    "appliesTo": "Indian Residents and NRIs",
    "examples": null,
    "documents": "Same document as earlier submitted (if still valid PDB document), or Self-declaration (Annex-II for adults or Annex-IIA for children)",
    "exceptions": "DoB update count shall not be increased for such cases. Applicable to NRIs except NRIs below 18 years may submit Birth Certificate or Indian Passport.",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": false,
    "annexureAdult": "Annex-II (self-declaration)",
    "annexureMinor": "Annex-IIA (self-declaration)"
  },
  {
    "code": "Case 2 b)",
    "category": "Operator Error",
    "description": "Cases where operator error is alleged during subsequent DoB update",
    "appliesTo": "Indian Residents / NRIs",
    "examples": null,
    "documents": "Same document as earlier submitted (if still valid PDB document), or Self-declaration (Annex-II for adults or Annex-IIA for children)",
    "exceptions": "The DoB update count shall not be increased for such cases.",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": false,
    "annexureAdult": "Annex-II (self-declaration)",
    "annexureMinor": "Annex-IIA (self-declaration)"
  },
  {
    "code": "Case 5 a)",
    "category": "Operator Error",
    "description": "Resident Foreigners DoB updates (DoB in Aadhaar differs from Pol cum PDB document due to operator error)",
    "appliesTo": "Resident Foreigners",
    "examples": null,
    "documents": "PoI cum PDB document and Self-declaration (Annex-II)",
    "exceptions": "DoB update count shall not be increased. Packet moves through normal QC flow and visible on QC portal.",
    "source": "Dt. 26.11.2025 SOP for DOB update in Aadhaar-reg. (Annexure 1,1A,2,2A,3,3A (3)-1.pdf",
    "blocked": false,
    "annexureAdult": "Annex-II (self-declaration)",
    "annexureMinor": "Annex-II (self-declaration)"
  }
];